name: Daily Image Processing Task

on:
  schedule:
    # This runs at 00:00 (Midnight) UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to trigger the script manually from the Actions tab

jobs:
  run-sender:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas tqdm

      - name: Run sender script
        env:
          API_URL: ${{ secrets.API_URL }}
        run: python sender.py